# Generated by Django 5.2 on 2025-05-03 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise_name", models.CharField(max_length=200)),
                ("exercise_type", models.CharField(max_length=100)),
                ("duration", models.IntegerField(help_text="Duration in minutes")),
                ("calories_burned", models.IntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("sets", models.IntegerField(blank=True, null=True)),
                ("reps", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
