# Generated by Django 5.2 on 2025-05-03 23:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "Tracker",
            "0005_remove_userprofile_height_cm_userprofile_height_feet_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="target_weight_kg",
            new_name="target_weight_lbs",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="weight_kg",
            new_name="weight_lbs",
        ),
    ]
